config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  namespace :users_backoffice do
    get 'welcome/index'
  end

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  resources :battle
  devise_for :users
  resources :bagmons
  resources :types
  resources :bagmons
  resources :types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bagmon.rb
class Bagmon < ApplicationRecord
    belongs_to :type
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :bagmons
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    
    def after_sign_in_path_for(resource_or_scope)
        '/bagmons'
    end
      
    def after_sign_out_path_for(resource_or_scope)
        '/users/sign_out'
    end

end

app/controllers/bagmons_controller.rb
class BagmonsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bagmon, only: %i[ show edit update destroy ]
  before_action :set_type_options, only: %i[ create new edit update ]

  # GET /bagmons or /bagmons.json
  def index
    @bagmons = Bagmon.all
  end

  # GET /bagmons/1 or /bagmons/1.json
  def show
  end

  # GET /bagmons/new
  def new
    @bagmon = Bagmon.new
  end

  # GET /bagmons/1/edit
  def edit
  end

  # POST /bagmons or /bagmons.json
  def create
    @bagmon = Bagmon.new(bagmon_params)

    respond_to do |format|
      if @bagmon.save
        format.html { redirect_to bagmon_url(@bagmon), notice: "Bagmon was successfully created." }
        format.json { render :show, status: :created, location: @bagmon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bagmon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bagmons/1 or /bagmons/1.json
  def update
    respond_to do |format|
      if @bagmon.update(bagmon_params)
        format.html { redirect_to bagmon_url(@bagmon), notice: "Bagmon was successfully updated." }
        format.json { render :show, status: :ok, location: @bagmon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bagmon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bagmons/1 or /bagmons/1.json
  def destroy
    @bagmon.destroy

    respond_to do |format|
      format.html { redirect_to bagmons_url, notice: "Bagmon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bagmon
      @bagmon = Bagmon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bagmon_params
      params.require(:bagmon).permit(:name, :number, :image, :type_id)
    end

    def set_type_options
      @type_options = Type.all.pluck(:name, :id)
    end
    
end

app/controllers/battle_controller.rb
class BattleController < ApplicationController
    before_action :authenticate_user!

    def index
        @bagmons = Bagmon.all
    
        if (params[:firstBagmon] && params[:secondBagmon]) 
          @firstBagmon = Bagmon.find(params[:firstBagmon])
          @secondBagmon = Bagmon.find(params[:secondBagmon])
          @rounds = []
    
          lifefirstBagmon = 100
          lifesecondBagmon = 100
    
          # Random bagmon attack first
          bagmonAttacking = rand(1..2) == 1 ? @firstBagmon : @secondBagmon
    
    
          while (lifefirstBagmon > 0 && lifesecondBagmon > 0) do
    
            # Bagmon 1 attack bagmon 2 and remove random between 5 adn 10 life points
    
            if (bagmonAttacking == @firstBagmon)
              attack = rand(5..15)
              lifesecondBagmon -= attack
              @rounds << @firstBagmon.name + " atacou " + @secondBagmon.name+ " e infligiu #{attack} de dano."
              bagmonAttacking = @secondBagmon
            else
              attack = rand(5..15)
              lifefirstBagmon -= attack
              @rounds << @secondBagmon.name + " atacou " + @firstBagmon.name + " e infligiu #{attack} de dano."
              bagmonAttacking = @firstBagmon
            end
          end
    
          # Display winner
          if (lifefirstBagmon <= 0)
            @rounds << @secondBagmon.name + ", o Bagmon aliado venceu!"
          elsif (lifesecondBagmon <= 0)
            @rounds << @firstBagmon.name + ", o Bagmon inimigo venceu!"
          end
        end
    
      end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_type, only: %i[ show edit update destroy ]

  # GET /types or /types.json
  def index
    @types = Type.all
  end

  # GET /types/1 or /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types or /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to type_url(@type), notice: "Type was successfully created." }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1 or /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to type_url(@type), notice: "Type was successfully updated." }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1 or /types/1.json
  def destroy
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url, notice: "Type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_params
      params.require(:type).permit(:name, :color)
    end
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < ApplicationController
  def index
  end
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
    before_action :authenticate_user!
    layout 'users_backoffice'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bagmons_helper.rb
module BagmonsHelper
end

app/helpers/battle_helper.rb
module BattleHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/bagmons/_form.html.erb
<%= form_with(model: bagmon, local: true) do |form| %>
  <% if bagmon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bagmon.errors.count, "error") %> prohibited this bagmon from being saved:</h2>

      <ul>
      <% bagmon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :type_id %>
    <%= form.number_field :type_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bagmons/edit.html.erb
<h1>Editing Bagmon</h1>

<%= render 'form', bagmon: @bagmon %>

<%= link_to 'Show', @bagmon %> |
<%= link_to 'Back', bagmons_path %>

app/views/bagmons/index.html.erb
<%= stylesheet_link_tag 'bagmon.css' %>


<body style="background-color: #FFF; padding: 3%">
  <div>
  <p id="notice"><%= notice %></p>
    <div class="container-description">
      <div class="bagmon-description"><h1><strong>Bagmons</strong></h1></div>
      <div class="batalha-description"><h2><%= link_to 'Batalha', battle_index_path, class: "bagmons-to-battle-link" %></h2></div>
    </div>

    <div id="bagmon-shelf">
      <% @bagmons.each do |bagmon| %>
          <div id="bagmon-card ">
            <div id="bagmon-name"><h2><%= bagmon.name %></h2></div>
            <div id="bagmon-image">
              <%= link_to (image_tag(bagmon.image, alt: 'fun', style: 'height:300px; width:auto;')), bagmon %>
            </div>
          </div>
        </a>
      <% end %>
    </div>

  </div>
  <br>
</body>

app/views/bagmons/new.html.erb
<h1>New Bagmon</h1>

<%= render 'form', bagmon: @bagmon %>

<%= link_to 'Back', bagmons_path %>

app/views/bagmons/show.html.erb
<%= stylesheet_link_tag 'bagmon-detail.css' %>

<p id="notice"><%= notice %></p>

<body style='background: <%=@bagmon.type.color %>; '>
  <div><%= link_to '←', bagmons_path, class: "arrow-back" %></div>

  <div id="display-bag-detail">
    <div>
      <div id=detail-name-and-type>
        <h1><%=@bagmon.name.upcase%></h1>
      </div>
      <p id="bag-detail-image"><%= image_tag @bagmon.image, alt: 'fun', style: 'height:400px; width:auto;'%></p>
      <p>Elemento: <%= @bagmon.type.name%></p>
    </div>
  </div>
</body>

app/views/battle/index.html.erb
 <body style="background-color: #FFF; padding:3%; flex-direction:column; display:flex; color:#FFF">
    <div><%= link_to '←', bagmons_path, class: "arrow-back" %></div>
    <div id='data' style="visibility: hidden;"><%= @rounds %></div>
    <div style="">
        <% if @firstBagmon && @secondBagmon %>
            <div id="result" style="background-color: ;">
                <h2 style="text-align: center; font-weight:bold; font-size: 20px;">Result</h2>
                <div style="flex-direction:row; display:flex; justify-content:center; align-items: center;">
                    <div>
                        <%= image_tag(@firstBagmon.image, alt: 'fun', style: 'height:300px; width:auto;')%>
                    </div>
                    <div>
                        <%= image_tag("vs.png", alt: 'fun', style: 'height:300px; width:auto;')%>
                    </div>
                    <div>
                        <%= image_tag(@secondBagmon.image, alt: 'fun', style: 'height:300px; width:auto;')%>
                    </div>
                </div>
            </div>
        <% else %>
            <div id="titulo-batalha" style="text-align: center; font-weight:bold; font-size: 20px;"><label>Escolha um Bagmon para lutar</label></div>
            <form action="/battle">
                <div style="flex-direction:row; display:flex; justify-content:center; align-items: center;">
                    <div >
                        <label for="firstBagmon">Bagmon Aliado</label>
                        <select required id="firstBagmon" name="firstBagmon" class="form-control">
                            <option selected disabled>Selecionar Bagmon</option>
                            <% @bagmons.each do |bagmon| %>
                                <option value="<%= bagmon.id %>"><%= bagmon.name %></option>
                            <% end %>
                        </select>
                    </div>
                    <div style="padding:20px;">
                    <%= image_tag("vs.png", alt: 'fun', style: 'height:250px; width:auto;')%>
                    </div>
                    <div>
                        <label for="secondBagmon">Bagmon Inimigo</label>
                        <select required id="secondBagmon" name="secondBagmon">
                            <option selected disabled>Selecionar Bagmon</option>
                            <% @bagmons.each do |bagmon| %>
                                <option value="<%= bagmon.id %>"><%= bagmon.name %></option>
                            <% end %>
                        </select>
                    </div>
                </div>
                <div style="flex-direction:column; display:flex; justify-content:center; align-items: center;">
                    <button type="submit" class="btn btn-primary">INICIAR</button>
                </div>
            </form>
        <% end %>

        <% if @firstBagmon && @secondBagmon %>
            <script>
                console.log("Bagmon 1: <%= @firstBagmon.name %>")
                console.log("Bagmon 2: <%= @secondBagmon.name %>")

                const rounds = JSON.parse(document.getElementById('data').innerHTML)

                function delay(ms) {
                    return new Promise(resolve => setTimeout(resolve, ms));
                }

                async function battle() {
                    for (let i = 0; i < rounds.length; i++) {
                        await delay(400);
                        if(i % 2){
                            allign = "left"
                        }else{
                            allign = "right"
                        }
                        document.querySelector('#result').innerHTML += `<div style="background-color: #FFF; color: #000; text-align: ${allign};">${rounds[i]}</div>`

                        window.scrollTo(0, document.body.scrollHeight);
                    }
                }
                battle();
            </script>
        <% end %>
    </div>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bagbattle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/types/_form.html.erb
<%= form_with(model: type, local: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.name %></td>
        <td><%= type.color %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @type.color %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users_backoffice/welcome/controller.html.erb
<h1>UsersBackoffice::Welcome#controller</h1>
<p>Find me in app/views/users_backoffice/welcome/controller.html.erb</p>

app/views/users_backoffice/welcome/g.html.erb
<h1>UsersBackoffice::Welcome#g</h1>
<p>Find me in app/views/users_backoffice/welcome/g.html.erb</p>

app/views/users_backoffice/welcome/index.html.erb
<h1>UsersBackoffice::Welcome#index</h1>
<p>Find me in app/views/users_backoffice/welcome/index.html.erb</p>

app/views/users_backoffice/welcome/rails.html.erb
<h1>UsersBackoffice::Welcome#rails</h1>
<p>Find me in app/views/users_backoffice/welcome/rails.html.erb</p>

app/views/users_backoffice/welcome/users_backoffice.html.erb
<h1>UsersBackoffice::Welcome#users_backoffice</h1>
<p>Find me in app/views/users_backoffice/welcome/users_backoffice.html.erb</p>